namespace BookStoreRazorPages.Application.Entities
{
    public enum Nationality
    {
        Palestenian,
        Jordanian,
        American,
        British,
        Canadian,
        Chinese,
        French,
        German,
        Indian,
        Italian,
        Japanese,
        Mexican,
        Nigerian,
        Australian,
        Russian,
        SouthKorean,
        Brazilian,
        SouthAfrican,
        Spanish,
        Swedish,
        Turkish,
        Egyptian,
        Irish,
        Colombian
    }
}
